import type { CostRates } from './types'

// Generated from https://vercel.com/ai-gateway/models
// Run: pnpm pricing:sync
export const MODEL_PRICING_GENERATED: Record<string, CostRates> = {
  'alibaba/qwen-3-14b': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'alibaba/qwen-3-235b': { inputCostPerMillionTokens: 0.071, outputCostPerMillionTokens: 0.463, cacheReadCostPerMillionTokens: 0.11 },
  'alibaba/qwen-3-30b': { inputCostPerMillionTokens: 0.08, outputCostPerMillionTokens: 0.29 },
  'alibaba/qwen-3-32b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'alibaba/qwen3-235b-a22b-thinking': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.9 },
  'alibaba/qwen3-coder': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 1.6, cacheReadCostPerMillionTokens: 0.3 },
  'alibaba/qwen3-coder-30b-a3b': { inputCostPerMillionTokens: 0.07, outputCostPerMillionTokens: 0.27 },
  'alibaba/qwen3-coder-next': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.2 },
  'alibaba/qwen3-coder-plus': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5, cacheReadCostPerMillionTokens: 0.2 },
  'alibaba/qwen3-embedding-0.6b': { inputCostPerMillionTokens: 0.01, outputCostPerMillionTokens: 0 },
  'alibaba/qwen3-embedding-4b': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'alibaba/qwen3-embedding-8b': { inputCostPerMillionTokens: 0.05, outputCostPerMillionTokens: 0 },
  'alibaba/qwen3-max': { inputCostPerMillionTokens: 0.845, outputCostPerMillionTokens: 3.38, cacheReadCostPerMillionTokens: 0.24 },
  'alibaba/qwen3-max-preview': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.24 },
  'alibaba/qwen3-max-thinking': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.24 },
  'alibaba/qwen3-next-80b-a3b-instruct': { inputCostPerMillionTokens: 0.09, outputCostPerMillionTokens: 1.1 },
  'alibaba/qwen3-next-80b-a3b-thinking': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 1.5 },
  'alibaba/qwen3-vl-instruct': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.88, cacheReadCostPerMillionTokens: 0.11 },
  'alibaba/qwen3-vl-thinking': { inputCostPerMillionTokens: 0.22, outputCostPerMillionTokens: 0.88 },
  'amazon/nova-2-lite': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'amazon/nova-lite': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'amazon/nova-micro': { inputCostPerMillionTokens: 0.035, outputCostPerMillionTokens: 0.14 },
  'amazon/nova-pro': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 3.2 },
  'amazon/titan-embed-text-v2': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'anthropic/claude-3-haiku': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1.25, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.3 },
  'anthropic/claude-3-opus': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75 },
  'anthropic/claude-3.5-haiku': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 4, cacheReadCostPerMillionTokens: 0.08, cacheWriteCostPerMillionTokens: 1 },
  'anthropic/claude-3.5-sonnet': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'anthropic/claude-3.5-sonnet-20240620': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'anthropic/claude-3.7-sonnet': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'anthropic/claude-haiku-4.5': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5, cacheReadCostPerMillionTokens: 0.1, cacheWriteCostPerMillionTokens: 1.25 },
  'anthropic/claude-opus-4': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75, cacheReadCostPerMillionTokens: 1.5, cacheWriteCostPerMillionTokens: 18.75 },
  'anthropic/claude-opus-4.1': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75, cacheReadCostPerMillionTokens: 1.5, cacheWriteCostPerMillionTokens: 18.75 },
  'anthropic/claude-opus-4.5': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25, cacheReadCostPerMillionTokens: 0.5, cacheWriteCostPerMillionTokens: 6.25 },
  'anthropic/claude-opus-4.6': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25, cacheReadCostPerMillionTokens: 0.5, cacheWriteCostPerMillionTokens: 6.25 },
  'anthropic/claude-sonnet-4': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'anthropic/claude-sonnet-4.5': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'arcee-ai/trinity-large-preview': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1 },
  'arcee-ai/trinity-mini': { inputCostPerMillionTokens: 0.045, outputCostPerMillionTokens: 0.15 },
  'bfl/flux-2-flex': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-2-klein-4b': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-2-klein-9b': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-2-max': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-2-pro': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-kontext-max': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-kontext-pro': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-pro-1.0-fill': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-pro-1.1': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bfl/flux-pro-1.1-ultra': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'bytedance/seed-1.6': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.05 },
  'bytedance/seed-1.8': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.05 },
  'claude-3-haiku': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1.25, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.3 },
  'claude-3-opus': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75 },
  'claude-3.5-haiku': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 4, cacheReadCostPerMillionTokens: 0.08, cacheWriteCostPerMillionTokens: 1 },
  'claude-3.5-sonnet': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'claude-3.5-sonnet-20240620': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'claude-3.7-sonnet': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'claude-haiku-4.5': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5, cacheReadCostPerMillionTokens: 0.1, cacheWriteCostPerMillionTokens: 1.25 },
  'claude-opus-4': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75, cacheReadCostPerMillionTokens: 1.5, cacheWriteCostPerMillionTokens: 18.75 },
  'claude-opus-4.1': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 75, cacheReadCostPerMillionTokens: 1.5, cacheWriteCostPerMillionTokens: 18.75 },
  'claude-opus-4.5': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25, cacheReadCostPerMillionTokens: 0.5, cacheWriteCostPerMillionTokens: 6.25 },
  'claude-opus-4.6': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25, cacheReadCostPerMillionTokens: 0.5, cacheWriteCostPerMillionTokens: 6.25 },
  'claude-sonnet-4': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'claude-sonnet-4.5': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15, cacheReadCostPerMillionTokens: 0.3, cacheWriteCostPerMillionTokens: 3.75 },
  'codestral': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.9 },
  'codestral-embed': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0 },
  'codex-mini': { inputCostPerMillionTokens: 1.5, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.375 },
  'cohere/command-a': { inputCostPerMillionTokens: 2.5, outputCostPerMillionTokens: 10 },
  'cohere/embed-v4.0': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'command-a': { inputCostPerMillionTokens: 2.5, outputCostPerMillionTokens: 10 },
  'deepseek-r1': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2.15, cacheReadCostPerMillionTokens: 0.4 },
  'deepseek-v3': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 0.77 },
  'deepseek-v3.1': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 1 },
  'deepseek-v3.1-terminus': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 1 },
  'deepseek-v3.2': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.028 },
  'deepseek-v3.2-exp': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 0.4 },
  'deepseek-v3.2-thinking': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 0.42, cacheReadCostPerMillionTokens: 0.028 },
  'deepseek/deepseek-r1': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2.15, cacheReadCostPerMillionTokens: 0.4 },
  'deepseek/deepseek-v3': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 0.77 },
  'deepseek/deepseek-v3.1': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 1 },
  'deepseek/deepseek-v3.1-terminus': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 1 },
  'deepseek/deepseek-v3.2': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.028 },
  'deepseek/deepseek-v3.2-exp': { inputCostPerMillionTokens: 0.27, outputCostPerMillionTokens: 0.4 },
  'deepseek/deepseek-v3.2-thinking': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 0.42, cacheReadCostPerMillionTokens: 0.028 },
  'devstral-2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'devstral-small': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'devstral-small-2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'embed-v4.0': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'flux-2-flex': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-2-klein-4b': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-2-klein-9b': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-2-max': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-2-pro': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-kontext-max': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-kontext-pro': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-pro-1.0-fill': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-pro-1.1': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'flux-pro-1.1-ultra': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'gemini-2.0-flash': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.025 },
  'gemini-2.0-flash-lite': { inputCostPerMillionTokens: 0.075, outputCostPerMillionTokens: 0.3 },
  'gemini-2.5-flash': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5, cacheReadCostPerMillionTokens: 0.03 },
  'gemini-2.5-flash-image': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'gemini-2.5-flash-image-preview': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'gemini-2.5-flash-lite': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
  'gemini-2.5-flash-lite-preview-09-2025': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
  'gemini-2.5-flash-preview-09-2025': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5, cacheReadCostPerMillionTokens: 0.03 },
  'gemini-2.5-pro': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gemini-3-flash': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 3, cacheReadCostPerMillionTokens: 0.05 },
  'gemini-3-pro-image': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 120 },
  'gemini-3-pro-preview': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 12, cacheReadCostPerMillionTokens: 0.2 },
  'gemini-embedding-001': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0 },
  'glm-4.5': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 2.2, cacheReadCostPerMillionTokens: 0.11 },
  'glm-4.5-air': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.1, cacheReadCostPerMillionTokens: 0.03 },
  'glm-4.5v': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 1.8, cacheReadCostPerMillionTokens: 0.11 },
  'glm-4.6': { inputCostPerMillionTokens: 0.45, outputCostPerMillionTokens: 1.8, cacheReadCostPerMillionTokens: 0.11 },
  'glm-4.6v': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.9, cacheReadCostPerMillionTokens: 0.05 },
  'glm-4.6v-flash': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'glm-4.7': { inputCostPerMillionTokens: 0.43, outputCostPerMillionTokens: 1.75, cacheReadCostPerMillionTokens: 0.08 },
  'glm-4.7-flash': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'glm-4.7-flashx': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
  'google/gemini-2.0-flash': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.025 },
  'google/gemini-2.0-flash-lite': { inputCostPerMillionTokens: 0.075, outputCostPerMillionTokens: 0.3 },
  'google/gemini-2.5-flash': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5, cacheReadCostPerMillionTokens: 0.03 },
  'google/gemini-2.5-flash-image': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'google/gemini-2.5-flash-image-preview': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'google/gemini-2.5-flash-lite': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
  'google/gemini-2.5-flash-lite-preview-09-2025': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
  'google/gemini-2.5-flash-preview-09-2025': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5, cacheReadCostPerMillionTokens: 0.03 },
  'google/gemini-2.5-pro': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'google/gemini-3-flash': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 3, cacheReadCostPerMillionTokens: 0.05 },
  'google/gemini-3-pro-image': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 120 },
  'google/gemini-3-pro-preview': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 12, cacheReadCostPerMillionTokens: 0.2 },
  'google/gemini-embedding-001': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0 },
  'google/imagen-4.0-fast-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'google/imagen-4.0-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'google/imagen-4.0-ultra-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'google/text-embedding-005': { inputCostPerMillionTokens: 0.025, outputCostPerMillionTokens: 0 },
  'google/text-multilingual-embedding-002': { inputCostPerMillionTokens: 0.025, outputCostPerMillionTokens: 0 },
  'gpt-3.5-turbo': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'gpt-3.5-turbo-instruct': { inputCostPerMillionTokens: 1.5, outputCostPerMillionTokens: 2 },
  'gpt-4-turbo': { inputCostPerMillionTokens: 10, outputCostPerMillionTokens: 30 },
  'gpt-4.1': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.5 },
  'gpt-4.1-mini': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 1.6, cacheReadCostPerMillionTokens: 0.1 },
  'gpt-4.1-nano': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.025 },
  'gpt-4o': { inputCostPerMillionTokens: 2.5, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 1.25 },
  'gpt-4o-mini': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6, cacheReadCostPerMillionTokens: 0.075 },
  'gpt-4o-mini-search-preview': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6 },
  'gpt-5': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5-chat': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5-codex': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5-mini': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.025 },
  'gpt-5-nano': { inputCostPerMillionTokens: 0.05, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.005 },
  'gpt-5-pro': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 120 },
  'gpt-5.1-codex': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5.1-codex-max': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5.1-codex-mini': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.025 },
  'gpt-5.1-instant': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5.1-thinking': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'gpt-5.2': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'gpt-5.2-chat': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'gpt-5.2-codex': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'gpt-5.2-pro': { inputCostPerMillionTokens: 21, outputCostPerMillionTokens: 168 },
  'gpt-oss-120b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.08 },
  'gpt-oss-20b': { inputCostPerMillionTokens: 0.07, outputCostPerMillionTokens: 0.3 },
  'gpt-oss-safeguard-20b': { inputCostPerMillionTokens: 0.075, outputCostPerMillionTokens: 0.3, cacheReadCostPerMillionTokens: 0.037 },
  'grok-2-vision': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 10 },
  'grok-3': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'grok-3-fast': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25 },
  'grok-3-mini': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.5 },
  'grok-3-mini-fast': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 4 },
  'grok-4': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'grok-4-fast-non-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'grok-4-fast-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'grok-4.1-fast-non-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'grok-4.1-fast-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'grok-code-fast-1': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.5, cacheReadCostPerMillionTokens: 0.02 },
  'imagen-4.0-fast-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'imagen-4.0-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'imagen-4.0-ultra-generate-001': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'inception/mercury-coder-small': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1 },
  'intellect-3': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.1 },
  'kat-coder-pro-v1': { inputCostPerMillionTokens: 0.03, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.06 },
  'kimi-k2': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2 },
  'kimi-k2-0905': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 2.5 },
  'kimi-k2-thinking': { inputCostPerMillionTokens: 0.47, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.141 },
  'kimi-k2-thinking-turbo': { inputCostPerMillionTokens: 1.15, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.15 },
  'kimi-k2-turbo': { inputCostPerMillionTokens: 2.4, outputCostPerMillionTokens: 10 },
  'kimi-k2.5': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2.8, cacheReadCostPerMillionTokens: 0.1 },
  'kwaipilot/kat-coder-pro-v1': { inputCostPerMillionTokens: 0.03, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.06 },
  'llama-3.1-70b': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 0.4 },
  'llama-3.1-8b': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0.05 },
  'llama-3.2-11b': { inputCostPerMillionTokens: 0.16, outputCostPerMillionTokens: 0.16 },
  'llama-3.2-1b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.1 },
  'llama-3.2-3b': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.15 },
  'llama-3.2-90b': { inputCostPerMillionTokens: 0.72, outputCostPerMillionTokens: 0.72 },
  'llama-3.3-70b': { inputCostPerMillionTokens: 0.59, outputCostPerMillionTokens: 0.72, cacheReadCostPerMillionTokens: 0.85 },
  'llama-4-maverick': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6 },
  'llama-4-scout': { inputCostPerMillionTokens: 0.08, outputCostPerMillionTokens: 0.3 },
  'longcat-flash-chat': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'longcat-flash-thinking': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 1.5 },
  'longcat-flash-thinking-2601': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'magistral-medium': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 5 },
  'magistral-small': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'meituan/longcat-flash-chat': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'meituan/longcat-flash-thinking': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 1.5 },
  'meituan/longcat-flash-thinking-2601': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'mercury-coder-small': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1 },
  'meta/llama-3.1-70b': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 0.4 },
  'meta/llama-3.1-8b': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0.05 },
  'meta/llama-3.2-11b': { inputCostPerMillionTokens: 0.16, outputCostPerMillionTokens: 0.16 },
  'meta/llama-3.2-1b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.1 },
  'meta/llama-3.2-3b': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.15 },
  'meta/llama-3.2-90b': { inputCostPerMillionTokens: 0.72, outputCostPerMillionTokens: 0.72 },
  'meta/llama-3.3-70b': { inputCostPerMillionTokens: 0.59, outputCostPerMillionTokens: 0.72, cacheReadCostPerMillionTokens: 0.85 },
  'meta/llama-4-maverick': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6 },
  'meta/llama-4-scout': { inputCostPerMillionTokens: 0.08, outputCostPerMillionTokens: 0.3 },
  'mimo-v2-flash': { inputCostPerMillionTokens: 0.09, outputCostPerMillionTokens: 0.29, cacheReadCostPerMillionTokens: 0.02 },
  'minimax-m2': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'minimax-m2.1': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'minimax-m2.1-lightning': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.4, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'minimax/minimax-m2': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'minimax/minimax-m2.1': { inputCostPerMillionTokens: 0.28, outputCostPerMillionTokens: 1.2, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'minimax/minimax-m2.1-lightning': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.4, cacheReadCostPerMillionTokens: 0.03, cacheWriteCostPerMillionTokens: 0.375 },
  'ministral-14b': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.2 },
  'ministral-3b': { inputCostPerMillionTokens: 0.04, outputCostPerMillionTokens: 0.04 },
  'ministral-8b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.1 },
  'mistral-embed': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0 },
  'mistral-large-3': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'mistral-medium': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 2 },
  'mistral-nemo': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0.04 },
  'mistral-small': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'mistral/codestral': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.9 },
  'mistral/codestral-embed': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0 },
  'mistral/devstral-2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'mistral/devstral-small': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'mistral/devstral-small-2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'mistral/magistral-medium': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 5 },
  'mistral/magistral-small': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'mistral/ministral-14b': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.2 },
  'mistral/ministral-3b': { inputCostPerMillionTokens: 0.04, outputCostPerMillionTokens: 0.04 },
  'mistral/ministral-8b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.1 },
  'mistral/mistral-embed': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0 },
  'mistral/mistral-large-3': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'mistral/mistral-medium': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 2 },
  'mistral/mistral-nemo': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0.04 },
  'mistral/mistral-small': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'mistral/mixtral-8x22b-instruct': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 1.2 },
  'mistral/pixtral-12b': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.15 },
  'mistral/pixtral-large': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 6 },
  'mixtral-8x22b-instruct': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 1.2 },
  'moonshotai/kimi-k2': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2 },
  'moonshotai/kimi-k2-0905': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 2.5 },
  'moonshotai/kimi-k2-thinking': { inputCostPerMillionTokens: 0.47, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.141 },
  'moonshotai/kimi-k2-thinking-turbo': { inputCostPerMillionTokens: 1.15, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.15 },
  'moonshotai/kimi-k2-turbo': { inputCostPerMillionTokens: 2.4, outputCostPerMillionTokens: 10 },
  'moonshotai/kimi-k2.5': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 2.8, cacheReadCostPerMillionTokens: 0.1 },
  'morph-v3-fast': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 1.2 },
  'morph-v3-large': { inputCostPerMillionTokens: 0.9, outputCostPerMillionTokens: 1.9 },
  'morph/morph-v3-fast': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 1.2 },
  'morph/morph-v3-large': { inputCostPerMillionTokens: 0.9, outputCostPerMillionTokens: 1.9 },
  'nemotron-3-nano-30b-a3b': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'nemotron-nano-12b-v2-vl': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.6 },
  'nemotron-nano-9b-v2': { inputCostPerMillionTokens: 0.04, outputCostPerMillionTokens: 0.16 },
  'nova-2-lite': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.5 },
  'nova-lite': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'nova-micro': { inputCostPerMillionTokens: 0.035, outputCostPerMillionTokens: 0.14 },
  'nova-pro': { inputCostPerMillionTokens: 0.8, outputCostPerMillionTokens: 3.2 },
  'nvidia/nemotron-3-nano-30b-a3b': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'nvidia/nemotron-nano-12b-v2-vl': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.6 },
  'nvidia/nemotron-nano-9b-v2': { inputCostPerMillionTokens: 0.04, outputCostPerMillionTokens: 0.16 },
  'o1': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 60, cacheReadCostPerMillionTokens: 7.5 },
  'o3': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.5 },
  'o3-deep-research': { inputCostPerMillionTokens: 10, outputCostPerMillionTokens: 40, cacheReadCostPerMillionTokens: 2.5 },
  'o3-mini': { inputCostPerMillionTokens: 1.1, outputCostPerMillionTokens: 4.4, cacheReadCostPerMillionTokens: 0.55 },
  'o3-pro': { inputCostPerMillionTokens: 20, outputCostPerMillionTokens: 80 },
  'o4-mini': { inputCostPerMillionTokens: 1.1, outputCostPerMillionTokens: 4.4, cacheReadCostPerMillionTokens: 0.275 },
  'openai/codex-mini': { inputCostPerMillionTokens: 1.5, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.375 },
  'openai/gpt-3.5-turbo': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.5 },
  'openai/gpt-3.5-turbo-instruct': { inputCostPerMillionTokens: 1.5, outputCostPerMillionTokens: 2 },
  'openai/gpt-4-turbo': { inputCostPerMillionTokens: 10, outputCostPerMillionTokens: 30 },
  'openai/gpt-4.1': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.5 },
  'openai/gpt-4.1-mini': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 1.6, cacheReadCostPerMillionTokens: 0.1 },
  'openai/gpt-4.1-nano': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.025 },
  'openai/gpt-4o': { inputCostPerMillionTokens: 2.5, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 1.25 },
  'openai/gpt-4o-mini': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6, cacheReadCostPerMillionTokens: 0.075 },
  'openai/gpt-4o-mini-search-preview': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.6 },
  'openai/gpt-5': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5-chat': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5-codex': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5-mini': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.025 },
  'openai/gpt-5-nano': { inputCostPerMillionTokens: 0.05, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.005 },
  'openai/gpt-5-pro': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 120 },
  'openai/gpt-5.1-codex': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5.1-codex-max': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5.1-codex-mini': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.025 },
  'openai/gpt-5.1-instant': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5.1-thinking': { inputCostPerMillionTokens: 1.25, outputCostPerMillionTokens: 10, cacheReadCostPerMillionTokens: 0.125 },
  'openai/gpt-5.2': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'openai/gpt-5.2-chat': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'openai/gpt-5.2-codex': { inputCostPerMillionTokens: 1.75, outputCostPerMillionTokens: 14, cacheReadCostPerMillionTokens: 0.175 },
  'openai/gpt-5.2-pro': { inputCostPerMillionTokens: 21, outputCostPerMillionTokens: 168 },
  'openai/gpt-oss-120b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.08 },
  'openai/gpt-oss-20b': { inputCostPerMillionTokens: 0.07, outputCostPerMillionTokens: 0.3 },
  'openai/gpt-oss-safeguard-20b': { inputCostPerMillionTokens: 0.075, outputCostPerMillionTokens: 0.3, cacheReadCostPerMillionTokens: 0.037 },
  'openai/o1': { inputCostPerMillionTokens: 15, outputCostPerMillionTokens: 60, cacheReadCostPerMillionTokens: 7.5 },
  'openai/o3': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8, cacheReadCostPerMillionTokens: 0.5 },
  'openai/o3-deep-research': { inputCostPerMillionTokens: 10, outputCostPerMillionTokens: 40, cacheReadCostPerMillionTokens: 2.5 },
  'openai/o3-mini': { inputCostPerMillionTokens: 1.1, outputCostPerMillionTokens: 4.4, cacheReadCostPerMillionTokens: 0.55 },
  'openai/o3-pro': { inputCostPerMillionTokens: 20, outputCostPerMillionTokens: 80 },
  'openai/o4-mini': { inputCostPerMillionTokens: 1.1, outputCostPerMillionTokens: 4.4, cacheReadCostPerMillionTokens: 0.275 },
  'openai/text-embedding-3-large': { inputCostPerMillionTokens: 0.13, outputCostPerMillionTokens: 0 },
  'openai/text-embedding-3-small': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'openai/text-embedding-ada-002': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0 },
  'perplexity/sonar': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 1 },
  'perplexity/sonar-pro': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'perplexity/sonar-reasoning': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5 },
  'perplexity/sonar-reasoning-pro': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8 },
  'pixtral-12b': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 0.15 },
  'pixtral-large': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 6 },
  'prime-intellect/intellect-3': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.1 },
  'qwen-3-14b': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.24 },
  'qwen-3-235b': { inputCostPerMillionTokens: 0.071, outputCostPerMillionTokens: 0.463, cacheReadCostPerMillionTokens: 0.11 },
  'qwen-3-30b': { inputCostPerMillionTokens: 0.08, outputCostPerMillionTokens: 0.29 },
  'qwen-3-32b': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0.3 },
  'qwen3-235b-a22b-thinking': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 2.9 },
  'qwen3-coder': { inputCostPerMillionTokens: 0.4, outputCostPerMillionTokens: 1.6, cacheReadCostPerMillionTokens: 0.3 },
  'qwen3-coder-30b-a3b': { inputCostPerMillionTokens: 0.07, outputCostPerMillionTokens: 0.27 },
  'qwen3-coder-next': { inputCostPerMillionTokens: 0.5, outputCostPerMillionTokens: 1.2 },
  'qwen3-coder-plus': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5, cacheReadCostPerMillionTokens: 0.2 },
  'qwen3-embedding-0.6b': { inputCostPerMillionTokens: 0.01, outputCostPerMillionTokens: 0 },
  'qwen3-embedding-4b': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'qwen3-embedding-8b': { inputCostPerMillionTokens: 0.05, outputCostPerMillionTokens: 0 },
  'qwen3-max': { inputCostPerMillionTokens: 0.845, outputCostPerMillionTokens: 3.38, cacheReadCostPerMillionTokens: 0.24 },
  'qwen3-max-preview': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.24 },
  'qwen3-max-thinking': { inputCostPerMillionTokens: 1.2, outputCostPerMillionTokens: 6, cacheReadCostPerMillionTokens: 0.24 },
  'qwen3-next-80b-a3b-instruct': { inputCostPerMillionTokens: 0.09, outputCostPerMillionTokens: 1.1 },
  'qwen3-next-80b-a3b-thinking': { inputCostPerMillionTokens: 0.15, outputCostPerMillionTokens: 1.5 },
  'qwen3-vl-instruct': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.88, cacheReadCostPerMillionTokens: 0.11 },
  'qwen3-vl-thinking': { inputCostPerMillionTokens: 0.22, outputCostPerMillionTokens: 0.88 },
  'recraft-v2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'recraft-v3': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'recraft/recraft-v2': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'recraft/recraft-v3': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'seed-1.6': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.05 },
  'seed-1.8': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 2, cacheReadCostPerMillionTokens: 0.05 },
  'sonar': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 1 },
  'sonar-pro': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'sonar-reasoning': { inputCostPerMillionTokens: 1, outputCostPerMillionTokens: 5 },
  'sonar-reasoning-pro': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 8 },
  'text-embedding-005': { inputCostPerMillionTokens: 0.025, outputCostPerMillionTokens: 0 },
  'text-embedding-3-large': { inputCostPerMillionTokens: 0.13, outputCostPerMillionTokens: 0 },
  'text-embedding-3-small': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'text-embedding-ada-002': { inputCostPerMillionTokens: 0.1, outputCostPerMillionTokens: 0 },
  'text-multilingual-embedding-002': { inputCostPerMillionTokens: 0.025, outputCostPerMillionTokens: 0 },
  'titan-embed-text-v2': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'trinity-large-preview': { inputCostPerMillionTokens: 0.25, outputCostPerMillionTokens: 1 },
  'trinity-mini': { inputCostPerMillionTokens: 0.045, outputCostPerMillionTokens: 0.15 },
  'v0-1.0-md': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'v0-1.5-md': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'vercel/v0-1.0-md': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'vercel/v0-1.5-md': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'voyage-3-large': { inputCostPerMillionTokens: 0.18, outputCostPerMillionTokens: 0 },
  'voyage-3.5': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0 },
  'voyage-3.5-lite': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'voyage-code-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'voyage-code-3': { inputCostPerMillionTokens: 0.18, outputCostPerMillionTokens: 0 },
  'voyage-finance-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'voyage-law-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'voyage/voyage-3-large': { inputCostPerMillionTokens: 0.18, outputCostPerMillionTokens: 0 },
  'voyage/voyage-3.5': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0 },
  'voyage/voyage-3.5-lite': { inputCostPerMillionTokens: 0.02, outputCostPerMillionTokens: 0 },
  'voyage/voyage-code-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'voyage/voyage-code-3': { inputCostPerMillionTokens: 0.18, outputCostPerMillionTokens: 0 },
  'voyage/voyage-finance-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'voyage/voyage-law-2': { inputCostPerMillionTokens: 0.12, outputCostPerMillionTokens: 0 },
  'xai/grok-2-vision': { inputCostPerMillionTokens: 2, outputCostPerMillionTokens: 10 },
  'xai/grok-3': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'xai/grok-3-fast': { inputCostPerMillionTokens: 5, outputCostPerMillionTokens: 25 },
  'xai/grok-3-mini': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.5 },
  'xai/grok-3-mini-fast': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 4 },
  'xai/grok-4': { inputCostPerMillionTokens: 3, outputCostPerMillionTokens: 15 },
  'xai/grok-4-fast-non-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'xai/grok-4-fast-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'xai/grok-4.1-fast-non-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'xai/grok-4.1-fast-reasoning': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 0.5, cacheReadCostPerMillionTokens: 0.05 },
  'xai/grok-code-fast-1': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.5, cacheReadCostPerMillionTokens: 0.02 },
  'xiaomi/mimo-v2-flash': { inputCostPerMillionTokens: 0.09, outputCostPerMillionTokens: 0.29, cacheReadCostPerMillionTokens: 0.02 },
  'zai/glm-4.5': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 2.2, cacheReadCostPerMillionTokens: 0.11 },
  'zai/glm-4.5-air': { inputCostPerMillionTokens: 0.2, outputCostPerMillionTokens: 1.1, cacheReadCostPerMillionTokens: 0.03 },
  'zai/glm-4.5v': { inputCostPerMillionTokens: 0.6, outputCostPerMillionTokens: 1.8, cacheReadCostPerMillionTokens: 0.11 },
  'zai/glm-4.6': { inputCostPerMillionTokens: 0.45, outputCostPerMillionTokens: 1.8, cacheReadCostPerMillionTokens: 0.11 },
  'zai/glm-4.6v': { inputCostPerMillionTokens: 0.3, outputCostPerMillionTokens: 0.9, cacheReadCostPerMillionTokens: 0.05 },
  'zai/glm-4.6v-flash': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'zai/glm-4.7': { inputCostPerMillionTokens: 0.43, outputCostPerMillionTokens: 1.75, cacheReadCostPerMillionTokens: 0.08 },
  'zai/glm-4.7-flash': { inputCostPerMillionTokens: 0, outputCostPerMillionTokens: 0 },
  'zai/glm-4.7-flashx': { inputCostPerMillionTokens: 0.06, outputCostPerMillionTokens: 0.4, cacheReadCostPerMillionTokens: 0.01 },
}
