packages:
  - docs
  - playground
catalog:
  next: ^16.1.6
  react: ^19.2.4
  react-dom: ^19.2.4
  workflow: ^4.1.0-beta.52
catalogs:
  build:
    tsdown: ^0.15.0
  docs:
    nuxt: ^4.3.0
    undocs: ^0.4.16
  lint:
    '@antfu/eslint-config': ^4.0.0
    eslint: ^9.0.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  prod:
    hookable: ^6.0.1
    pathe: ^2.0.3
    std-env: ^3.10.0
    yaml: ^2.7.0
  sandbox:
    '@cloudflare/sandbox': ^0.7.0
    '@vercel/node': ^5.1.10
    '@vercel/sandbox': ^1.4.1
  script:
    bumpp: ^9.0.0
  test:
    vitest: ^3.0.0
  types:
    '@types/node': ^25.1.0
    typescript: ^5.7.0
  vector:
    '@libsql/client': ^0.17.0
    '@pinecone-database/pinecone': ^7.0.0
    '@qdrant/js-client-rest': ^1.16.2
    '@upstash/vector': ^1.2.2
    pg: ^8.18.0
    sqlite-vec: 0.1.7-alpha.2
    weaviate-client: ^3.11.0
onlyBuiltDependencies:
  - simple-git-hooks
