packages:
  - docs
  - playground
catalog:
  '@netlify/async-workloads': ^0.0.106
  '@netlify/blobs': ^10.6.0
  '@nuxt/ui': ^4.4.0
  '@openworkflow/backend-postgres': ^0.6.0
  '@vercel/queue': ^0.0.0-alpha.36
  '@vitejs/plugin-vue': ^5
  '@vueuse/core': ^12
  h3: ^1.15.5
  nitropack: ^2.13.1
  openworkflow: ^0.6.6
  tailwindcss: ^4
  vite: ^6
  vue: ^3
  vue-router: ^4
  workflow: ^4.1.0-beta.52
catalogs:
  build:
    tsdown: ^0.15.0
  docs:
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/simple-icons': ^1.2.69
    '@iconify-json/vscode-icons': ^1.2.40
    '@nuxtjs/mdc': ^0.20.0
    nuxt: ^4.3.0
    undocs: ^0.4.16
    unist-util-visit: ^5.1.0
  lint:
    '@antfu/eslint-config': ^4.0.0
    eslint: ^9.0.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  prod:
    ajv: ^8.17.1
    croner: ^9.0.0
    hookable: ^6.0.1
    pathe: ^2.0.3
    std-env: ^3.10.0
    yaml: ^2.7.0
  sandbox:
    '@cloudflare/sandbox': ^0.7.0
    '@vercel/node': ^5.1.10
    '@vercel/sandbox': ^1.4.1
  script:
    bumpp: ^9.0.0
  test:
    vitest: ^3.0.0
  types:
    '@types/node': ^25.1.0
    typescript: ^5.7.0
  vector:
    '@libsql/client': ^0.17.0
    '@pinecone-database/pinecone': ^7.0.0
    '@qdrant/js-client-rest': ^1.16.2
    '@upstash/vector': ^1.2.2
    pg: ^8.18.0
    sqlite-vec: 0.1.7-alpha.2
    weaviate-client: ^3.11.0
onlyBuiltDependencies:
  - simple-git-hooks
