import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/env/index.ts',
    'src/fs/index.ts',
    'src/task/index.ts',
    'src/queue/index.ts',
    'src/sandbox/index.ts',
    'src/workflow/index.ts',
    'src/skill/index.ts',
    'src/usage/index.ts',
    'src/vector/index.ts',
    'src/vector/adapters/base.ts',
    'src/vector/adapters/cloudflare.ts',
    'src/vector/adapters/upstash.ts',
    'src/vector/adapters/pgvector.ts',
    'src/vector/adapters/libsql.ts',
    'src/vector/adapters/sqlite-vec.ts',
    'src/vector/adapters/pinecone.ts',
    'src/vector/adapters/qdrant.ts',
    'src/vector/adapters/weaviate.ts',
    'src/vector/embeddings/index.ts',
    'src/vector/embeddings/openai.ts',
    'src/vector/embeddings/cohere.ts',
    'src/vector/embeddings/google.ts',
    'src/vector/embeddings/mistral.ts',
    'src/vector/embeddings/ollama.ts',
    'src/vector/embeddings/transformers-js.ts',
    'src/vector/embeddings/resolve.ts',
    'src/vector/embeddings/model-info.ts',
    'src/vercel/index.ts',
  ],
  format: 'esm',
  dts: true,
  clean: true,
})
